version: '3.8'

services:
  app:
    build: .
    container_name: film-log-app
    ports:
      - "3000:3000"
    volumes:
      - film_data:/app/data
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"   # ログファイルの最大サイズ（例: 10MB）
        max-file: "3"     # 保存するログファイルの最大世代数

volumes:
  film_data: